version: 1
accounts:
- name: alice
  mnemonic: message another leisure emotion flush path cigar tunnel august sport vocal mango unusual people grain assist filter private bridge wink sniff decrease endless wagon
  coins:
  - 200000000ufront
- name: bob
  mnemonic: van almost scheme above bleak rely response leisure process victory sustain bottom nation vocal include volcano tattoo negative help sudden repeat case betray naive
  coins:
  - 100000000ufront
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000ufront
validators:
- name: alice
  bonded: 100000000ufront
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ufront"
    migration:
      migratorList:
        - migrator: front1rnqvu55fxndcqw920rvpgl06fjr0hjedcl5vjx
          exists: true
        