// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: selfchain/keyless/network.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// KeyType defines the type of cryptographic key
type KeyType int32

const (
	// Unspecified key type
	KeyType_KEY_TYPE_UNSPECIFIED KeyType = 0
	// ECDSA key type
	KeyType_KEY_TYPE_ECDSA KeyType = 1
	// EdDSA key type
	KeyType_KEY_TYPE_EDDSA KeyType = 2
	// BLS key type
	KeyType_KEY_TYPE_BLS KeyType = 3
	// Schnorr key type
	KeyType_KEY_TYPE_SCHNORR KeyType = 4
)

var KeyType_name = map[int32]string{
	0: "KEY_TYPE_UNSPECIFIED",
	1: "KEY_TYPE_ECDSA",
	2: "KEY_TYPE_EDDSA",
	3: "KEY_TYPE_BLS",
	4: "KEY_TYPE_SCHNORR",
}

var KeyType_value = map[string]int32{
	"KEY_TYPE_UNSPECIFIED": 0,
	"KEY_TYPE_ECDSA":       1,
	"KEY_TYPE_EDDSA":       2,
	"KEY_TYPE_BLS":         3,
	"KEY_TYPE_SCHNORR":     4,
}

func (x KeyType) String() string {
	return proto.EnumName(KeyType_name, int32(x))
}

func (KeyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c830b3db207baaa, []int{0}
}

// NetworkParams defines the parameters for network-specific signing operations
type NetworkParams struct {
	NetworkType      string         `protobuf:"bytes,1,opt,name=network_type,json=networkType,proto3" json:"network_type,omitempty"`
	ChainId          string         `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	SigningAlgorithm string         `protobuf:"bytes,3,opt,name=signing_algorithm,json=signingAlgorithm,proto3" json:"signing_algorithm,omitempty"`
	CurveType        string         `protobuf:"bytes,4,opt,name=curve_type,json=curveType,proto3" json:"curve_type,omitempty"`
	AddressPrefix    string         `protobuf:"bytes,5,opt,name=address_prefix,json=addressPrefix,proto3" json:"address_prefix,omitempty"`
	CoinType         uint32         `protobuf:"varint,6,opt,name=coin_type,json=coinType,proto3" json:"coin_type,omitempty"`
	Decimals         uint32         `protobuf:"varint,7,opt,name=decimals,proto3" json:"decimals,omitempty"`
	SymbolName       string         `protobuf:"bytes,8,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`
	DisplayName      string         `protobuf:"bytes,9,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	SigningConfig    *SigningConfig `protobuf:"bytes,10,opt,name=signing_config,json=signingConfig,proto3" json:"signing_config,omitempty"`
	KeygenThreshold  uint32         `protobuf:"varint,11,opt,name=keygen_threshold,json=keygenThreshold,proto3" json:"keygen_threshold,omitempty"`
	SigningThreshold uint32         `protobuf:"varint,12,opt,name=signing_threshold,json=signingThreshold,proto3" json:"signing_threshold,omitempty"`
	KeyType          KeyType        `protobuf:"varint,13,opt,name=key_type,json=keyType,proto3,enum=selfchain.keyless.KeyType" json:"key_type,omitempty"`
}

func (m *NetworkParams) Reset()         { *m = NetworkParams{} }
func (m *NetworkParams) String() string { return proto.CompactTextString(m) }
func (*NetworkParams) ProtoMessage()    {}
func (*NetworkParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c830b3db207baaa, []int{0}
}
func (m *NetworkParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetworkParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetworkParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NetworkParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkParams.Merge(m, src)
}
func (m *NetworkParams) XXX_Size() int {
	return m.Size()
}
func (m *NetworkParams) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkParams.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkParams proto.InternalMessageInfo

func (m *NetworkParams) GetNetworkType() string {
	if m != nil {
		return m.NetworkType
	}
	return ""
}

func (m *NetworkParams) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *NetworkParams) GetSigningAlgorithm() string {
	if m != nil {
		return m.SigningAlgorithm
	}
	return ""
}

func (m *NetworkParams) GetCurveType() string {
	if m != nil {
		return m.CurveType
	}
	return ""
}

func (m *NetworkParams) GetAddressPrefix() string {
	if m != nil {
		return m.AddressPrefix
	}
	return ""
}

func (m *NetworkParams) GetCoinType() uint32 {
	if m != nil {
		return m.CoinType
	}
	return 0
}

func (m *NetworkParams) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *NetworkParams) GetSymbolName() string {
	if m != nil {
		return m.SymbolName
	}
	return ""
}

func (m *NetworkParams) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *NetworkParams) GetSigningConfig() *SigningConfig {
	if m != nil {
		return m.SigningConfig
	}
	return nil
}

func (m *NetworkParams) GetKeygenThreshold() uint32 {
	if m != nil {
		return m.KeygenThreshold
	}
	return 0
}

func (m *NetworkParams) GetSigningThreshold() uint32 {
	if m != nil {
		return m.SigningThreshold
	}
	return 0
}

func (m *NetworkParams) GetKeyType() KeyType {
	if m != nil {
		return m.KeyType
	}
	return KeyType_KEY_TYPE_UNSPECIFIED
}

// SigningConfig contains network-specific signing configuration
type SigningConfig struct {
	P2PkhPrefix   uint32 `protobuf:"varint,1,opt,name=p2pkh_prefix,json=p2pkhPrefix,proto3" json:"p2pkh_prefix,omitempty"`
	P2ShPrefix    uint32 `protobuf:"varint,2,opt,name=p2sh_prefix,json=p2shPrefix,proto3" json:"p2sh_prefix,omitempty"`
	Hrp           string `protobuf:"bytes,3,opt,name=hrp,proto3" json:"hrp,omitempty"`
	Base58Hasher  string `protobuf:"bytes,4,opt,name=base58_hasher,json=base58Hasher,proto3" json:"base58_hasher,omitempty"`
	ChainId       string `protobuf:"bytes,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	GasToken      string `protobuf:"bytes,6,opt,name=gas_token,json=gasToken,proto3" json:"gas_token,omitempty"`
	AddressPrefix string `protobuf:"bytes,7,opt,name=address_prefix,json=addressPrefix,proto3" json:"address_prefix,omitempty"`
	PubKeyPrefix  string `protobuf:"bytes,8,opt,name=pub_key_prefix,json=pubKeyPrefix,proto3" json:"pub_key_prefix,omitempty"`
}

func (m *SigningConfig) Reset()         { *m = SigningConfig{} }
func (m *SigningConfig) String() string { return proto.CompactTextString(m) }
func (*SigningConfig) ProtoMessage()    {}
func (*SigningConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c830b3db207baaa, []int{1}
}
func (m *SigningConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigningConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SigningConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SigningConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningConfig.Merge(m, src)
}
func (m *SigningConfig) XXX_Size() int {
	return m.Size()
}
func (m *SigningConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SigningConfig proto.InternalMessageInfo

func (m *SigningConfig) GetP2PkhPrefix() uint32 {
	if m != nil {
		return m.P2PkhPrefix
	}
	return 0
}

func (m *SigningConfig) GetP2ShPrefix() uint32 {
	if m != nil {
		return m.P2ShPrefix
	}
	return 0
}

func (m *SigningConfig) GetHrp() string {
	if m != nil {
		return m.Hrp
	}
	return ""
}

func (m *SigningConfig) GetBase58Hasher() string {
	if m != nil {
		return m.Base58Hasher
	}
	return ""
}

func (m *SigningConfig) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *SigningConfig) GetGasToken() string {
	if m != nil {
		return m.GasToken
	}
	return ""
}

func (m *SigningConfig) GetAddressPrefix() string {
	if m != nil {
		return m.AddressPrefix
	}
	return ""
}

func (m *SigningConfig) GetPubKeyPrefix() string {
	if m != nil {
		return m.PubKeyPrefix
	}
	return ""
}

func init() {
	proto.RegisterEnum("selfchain.keyless.KeyType", KeyType_name, KeyType_value)
	proto.RegisterType((*NetworkParams)(nil), "selfchain.keyless.NetworkParams")
	proto.RegisterType((*SigningConfig)(nil), "selfchain.keyless.SigningConfig")
}

func init() { proto.RegisterFile("selfchain/keyless/network.proto", fileDescriptor_1c830b3db207baaa) }

var fileDescriptor_1c830b3db207baaa = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xc7, 0x9b, 0xee, 0xa5, 0xc9, 0x93, 0xa6, 0x64, 0xd6, 0x0e, 0xd9, 0x26, 0xb2, 0x32, 0x40,
	0x2a, 0x20, 0x75, 0x52, 0xa7, 0x49, 0x5c, 0xb7, 0xae, 0xb0, 0x69, 0xa8, 0x54, 0x69, 0x39, 0x8c,
	0x4b, 0xe4, 0x36, 0x5e, 0x12, 0xe5, 0x55, 0x71, 0x06, 0xcb, 0xa7, 0x80, 0x0b, 0xdf, 0x89, 0xe3,
	0x8e, 0x1c, 0xd1, 0xf6, 0x45, 0x50, 0x6c, 0x27, 0x5b, 0x45, 0x6f, 0xf1, 0xcf, 0xbf, 0x3e, 0x76,
	0xff, 0xcf, 0x63, 0xd8, 0xa7, 0x24, 0xbc, 0x5e, 0x78, 0xd8, 0x8f, 0x0f, 0x03, 0x52, 0x84, 0x84,
	0xd2, 0xc3, 0x98, 0xe4, 0xdf, 0x93, 0x2c, 0xe8, 0xa7, 0x59, 0x92, 0x27, 0x68, 0xab, 0x16, 0xfa,
	0x42, 0x38, 0xf8, 0xb5, 0x0e, 0xda, 0x98, 0x4b, 0x13, 0x9c, 0xe1, 0x88, 0xa2, 0x17, 0xd0, 0x16,
	0xbf, 0xb2, 0xf3, 0x22, 0x25, 0x86, 0xd4, 0x95, 0x7a, 0x8a, 0xa5, 0x0a, 0x36, 0x2b, 0x52, 0x82,
	0x76, 0x40, 0x66, 0x55, 0x6c, 0xdf, 0x31, 0x9a, 0x6c, 0xbb, 0xc5, 0xd6, 0x17, 0x0e, 0x7a, 0x07,
	0x5b, 0xd4, 0x77, 0x63, 0x3f, 0x76, 0x6d, 0x1c, 0xba, 0x49, 0xe6, 0xe7, 0x5e, 0x64, 0xac, 0x31,
	0x47, 0x17, 0x1b, 0x27, 0x15, 0x47, 0xcf, 0x01, 0x16, 0x37, 0xd9, 0x37, 0xc2, 0x0f, 0x5a, 0x67,
	0x96, 0xc2, 0x08, 0x3b, 0xe6, 0x35, 0x74, 0xb0, 0xe3, 0x64, 0x84, 0x52, 0x3b, 0xcd, 0xc8, 0xb5,
	0x7f, 0x6b, 0x6c, 0x30, 0x45, 0x13, 0x74, 0xc2, 0x20, 0xda, 0x03, 0x65, 0x91, 0xf8, 0x31, 0x2f,
	0xb2, 0xd9, 0x95, 0x7a, 0x9a, 0x25, 0x97, 0x80, 0xd5, 0xd8, 0x05, 0xd9, 0x21, 0x0b, 0x3f, 0xc2,
	0x21, 0x35, 0x5a, 0x7c, 0xaf, 0x5a, 0xa3, 0x7d, 0x50, 0x69, 0x11, 0xcd, 0x93, 0xd0, 0x8e, 0x71,
	0x44, 0x0c, 0x99, 0x15, 0x07, 0x8e, 0xc6, 0x38, 0x22, 0x65, 0x14, 0x8e, 0x4f, 0xd3, 0x10, 0x17,
	0xdc, 0x50, 0x78, 0x14, 0x82, 0x31, 0xe5, 0x23, 0x74, 0xaa, 0xff, 0xbb, 0x48, 0xe2, 0x6b, 0xdf,
	0x35, 0xa0, 0x2b, 0xf5, 0xd4, 0x41, 0xb7, 0xff, 0x5f, 0xd6, 0xfd, 0x29, 0x17, 0x87, 0xcc, 0xb3,
	0x34, 0xfa, 0x74, 0x89, 0xde, 0x80, 0x1e, 0x90, 0xc2, 0x25, 0xb1, 0x9d, 0x7b, 0x19, 0xa1, 0x5e,
	0x12, 0x3a, 0x86, 0xca, 0x2e, 0xfc, 0x8c, 0xf3, 0x59, 0x85, 0x9f, 0x66, 0xfc, 0xe8, 0xb6, 0x99,
	0x5b, 0x65, 0xfc, 0x28, 0x1f, 0x83, 0x1c, 0x90, 0x82, 0x87, 0xa3, 0x75, 0xa5, 0x5e, 0x67, 0xb0,
	0xbb, 0xe2, 0x6a, 0x97, 0xa4, 0x28, 0xe3, 0xb2, 0x5a, 0x01, 0xff, 0x38, 0xf8, 0xd1, 0x04, 0x6d,
	0xe9, 0xbe, 0x65, 0x18, 0xe9, 0x20, 0x0d, 0xbc, 0xaa, 0x17, 0x12, 0x3b, 0x50, 0x65, 0x4c, 0x74,
	0x62, 0x1f, 0xd4, 0x74, 0x40, 0x6b, 0xa3, 0xc9, 0x0c, 0x28, 0x91, 0x10, 0x74, 0x58, 0xf3, 0xb2,
	0x54, 0xcc, 0x43, 0xf9, 0x89, 0x5e, 0x82, 0x36, 0xc7, 0x94, 0x1c, 0xbf, 0xb7, 0x3d, 0x4c, 0x3d,
	0x92, 0x89, 0x29, 0x68, 0x73, 0x78, 0xce, 0xd8, 0xd2, 0xbc, 0x6d, 0x2c, 0xcf, 0xdb, 0x1e, 0x28,
	0x2e, 0xa6, 0x76, 0x9e, 0x04, 0x24, 0x66, 0xcd, 0x57, 0x2c, 0xd9, 0xc5, 0x74, 0x56, 0xae, 0x57,
	0x0c, 0x50, 0x6b, 0xd5, 0x00, 0xbd, 0x82, 0x4e, 0x7a, 0x33, 0xb7, 0xcb, 0x98, 0x84, 0xc6, 0x47,
	0xa1, 0x9d, 0xde, 0xcc, 0x2f, 0x49, 0xc1, 0xad, 0xb7, 0x14, 0x5a, 0x22, 0x25, 0x64, 0xc0, 0xf6,
	0xe5, 0xe8, 0xca, 0x9e, 0x5d, 0x4d, 0x46, 0xf6, 0x97, 0xf1, 0x74, 0x32, 0x1a, 0x5e, 0x7c, 0xb8,
	0x18, 0x9d, 0xe9, 0x0d, 0x84, 0xa0, 0x53, 0xef, 0x8c, 0x86, 0x67, 0xd3, 0x13, 0x5d, 0x5a, 0x66,
	0x67, 0x25, 0x6b, 0x22, 0x1d, 0xda, 0x35, 0x3b, 0xfd, 0x34, 0xd5, 0xd7, 0xd0, 0x36, 0xe8, 0x35,
	0x99, 0x0e, 0xcf, 0xc7, 0x9f, 0x2d, 0x4b, 0x5f, 0x3f, 0x3d, 0xfa, 0x7d, 0x6f, 0x4a, 0x77, 0xf7,
	0xa6, 0xf4, 0xf7, 0xde, 0x94, 0x7e, 0x3e, 0x98, 0x8d, 0xbb, 0x07, 0xb3, 0xf1, 0xe7, 0xc1, 0x6c,
	0x7c, 0xdd, 0x79, 0x7c, 0xec, 0xb7, 0xf5, 0x73, 0x2f, 0xbb, 0x4c, 0xe7, 0x9b, 0xec, 0xb5, 0x1f,
	0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x72, 0x25, 0xb0, 0xaa, 0x10, 0x04, 0x00, 0x00,
}

func (m *NetworkParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetworkParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetworkParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.KeyType != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.KeyType))
		i--
		dAtA[i] = 0x68
	}
	if m.SigningThreshold != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.SigningThreshold))
		i--
		dAtA[i] = 0x60
	}
	if m.KeygenThreshold != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.KeygenThreshold))
		i--
		dAtA[i] = 0x58
	}
	if m.SigningConfig != nil {
		{
			size, err := m.SigningConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNetwork(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.SymbolName) > 0 {
		i -= len(m.SymbolName)
		copy(dAtA[i:], m.SymbolName)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.SymbolName)))
		i--
		dAtA[i] = 0x42
	}
	if m.Decimals != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x38
	}
	if m.CoinType != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.CoinType))
		i--
		dAtA[i] = 0x30
	}
	if len(m.AddressPrefix) > 0 {
		i -= len(m.AddressPrefix)
		copy(dAtA[i:], m.AddressPrefix)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.AddressPrefix)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CurveType) > 0 {
		i -= len(m.CurveType)
		copy(dAtA[i:], m.CurveType)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.CurveType)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SigningAlgorithm) > 0 {
		i -= len(m.SigningAlgorithm)
		copy(dAtA[i:], m.SigningAlgorithm)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.SigningAlgorithm)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.NetworkType) > 0 {
		i -= len(m.NetworkType)
		copy(dAtA[i:], m.NetworkType)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.NetworkType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SigningConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigningConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigningConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PubKeyPrefix) > 0 {
		i -= len(m.PubKeyPrefix)
		copy(dAtA[i:], m.PubKeyPrefix)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.PubKeyPrefix)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.AddressPrefix) > 0 {
		i -= len(m.AddressPrefix)
		copy(dAtA[i:], m.AddressPrefix)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.AddressPrefix)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.GasToken) > 0 {
		i -= len(m.GasToken)
		copy(dAtA[i:], m.GasToken)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.GasToken)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Base58Hasher) > 0 {
		i -= len(m.Base58Hasher)
		copy(dAtA[i:], m.Base58Hasher)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.Base58Hasher)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Hrp) > 0 {
		i -= len(m.Hrp)
		copy(dAtA[i:], m.Hrp)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.Hrp)))
		i--
		dAtA[i] = 0x1a
	}
	if m.P2ShPrefix != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.P2ShPrefix))
		i--
		dAtA[i] = 0x10
	}
	if m.P2PkhPrefix != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.P2PkhPrefix))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNetwork(dAtA []byte, offset int, v uint64) int {
	offset -= sovNetwork(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NetworkParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NetworkType)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.SigningAlgorithm)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.CurveType)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.AddressPrefix)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	if m.CoinType != 0 {
		n += 1 + sovNetwork(uint64(m.CoinType))
	}
	if m.Decimals != 0 {
		n += 1 + sovNetwork(uint64(m.Decimals))
	}
	l = len(m.SymbolName)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	if m.SigningConfig != nil {
		l = m.SigningConfig.Size()
		n += 1 + l + sovNetwork(uint64(l))
	}
	if m.KeygenThreshold != 0 {
		n += 1 + sovNetwork(uint64(m.KeygenThreshold))
	}
	if m.SigningThreshold != 0 {
		n += 1 + sovNetwork(uint64(m.SigningThreshold))
	}
	if m.KeyType != 0 {
		n += 1 + sovNetwork(uint64(m.KeyType))
	}
	return n
}

func (m *SigningConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.P2PkhPrefix != 0 {
		n += 1 + sovNetwork(uint64(m.P2PkhPrefix))
	}
	if m.P2ShPrefix != 0 {
		n += 1 + sovNetwork(uint64(m.P2ShPrefix))
	}
	l = len(m.Hrp)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.Base58Hasher)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.GasToken)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.AddressPrefix)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.PubKeyPrefix)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	return n
}

func sovNetwork(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNetwork(x uint64) (n int) {
	return sovNetwork(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NetworkParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNetwork
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetworkParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetworkParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigningAlgorithm", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SigningAlgorithm = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurveType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurveType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinType", wireType)
			}
			m.CoinType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CoinType |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SymbolName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SymbolName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigningConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SigningConfig == nil {
				m.SigningConfig = &SigningConfig{}
			}
			if err := m.SigningConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeygenThreshold", wireType)
			}
			m.KeygenThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeygenThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SigningThreshold", wireType)
			}
			m.SigningThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SigningThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyType", wireType)
			}
			m.KeyType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeyType |= KeyType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNetwork(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNetwork
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SigningConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNetwork
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigningConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigningConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field P2PkhPrefix", wireType)
			}
			m.P2PkhPrefix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.P2PkhPrefix |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field P2ShPrefix", wireType)
			}
			m.P2ShPrefix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.P2ShPrefix |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hrp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hrp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base58Hasher", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Base58Hasher = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKeyPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKeyPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNetwork(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNetwork
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNetwork(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNetwork
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNetwork
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNetwork
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNetwork
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNetwork        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNetwork          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNetwork = fmt.Errorf("proto: unexpected end of group")
)
