// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: frontier/migration/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetTokenMigrationRequest struct {
	MsgHash string `protobuf:"bytes,1,opt,name=msgHash,proto3" json:"msgHash,omitempty"`
}

func (m *QueryGetTokenMigrationRequest) Reset()         { *m = QueryGetTokenMigrationRequest{} }
func (m *QueryGetTokenMigrationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTokenMigrationRequest) ProtoMessage()    {}
func (*QueryGetTokenMigrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{2}
}
func (m *QueryGetTokenMigrationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTokenMigrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTokenMigrationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTokenMigrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTokenMigrationRequest.Merge(m, src)
}
func (m *QueryGetTokenMigrationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTokenMigrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTokenMigrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTokenMigrationRequest proto.InternalMessageInfo

func (m *QueryGetTokenMigrationRequest) GetMsgHash() string {
	if m != nil {
		return m.MsgHash
	}
	return ""
}

type QueryGetTokenMigrationResponse struct {
	TokenMigration TokenMigration `protobuf:"bytes,1,opt,name=tokenMigration,proto3" json:"tokenMigration"`
}

func (m *QueryGetTokenMigrationResponse) Reset()         { *m = QueryGetTokenMigrationResponse{} }
func (m *QueryGetTokenMigrationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTokenMigrationResponse) ProtoMessage()    {}
func (*QueryGetTokenMigrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{3}
}
func (m *QueryGetTokenMigrationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTokenMigrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTokenMigrationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTokenMigrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTokenMigrationResponse.Merge(m, src)
}
func (m *QueryGetTokenMigrationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTokenMigrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTokenMigrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTokenMigrationResponse proto.InternalMessageInfo

func (m *QueryGetTokenMigrationResponse) GetTokenMigration() TokenMigration {
	if m != nil {
		return m.TokenMigration
	}
	return TokenMigration{}
}

type QueryAllTokenMigrationRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTokenMigrationRequest) Reset()         { *m = QueryAllTokenMigrationRequest{} }
func (m *QueryAllTokenMigrationRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTokenMigrationRequest) ProtoMessage()    {}
func (*QueryAllTokenMigrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{4}
}
func (m *QueryAllTokenMigrationRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTokenMigrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTokenMigrationRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTokenMigrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTokenMigrationRequest.Merge(m, src)
}
func (m *QueryAllTokenMigrationRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTokenMigrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTokenMigrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTokenMigrationRequest proto.InternalMessageInfo

func (m *QueryAllTokenMigrationRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllTokenMigrationResponse struct {
	TokenMigration []TokenMigration    `protobuf:"bytes,1,rep,name=tokenMigration,proto3" json:"tokenMigration"`
	Pagination     *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTokenMigrationResponse) Reset()         { *m = QueryAllTokenMigrationResponse{} }
func (m *QueryAllTokenMigrationResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTokenMigrationResponse) ProtoMessage()    {}
func (*QueryAllTokenMigrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{5}
}
func (m *QueryAllTokenMigrationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTokenMigrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTokenMigrationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTokenMigrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTokenMigrationResponse.Merge(m, src)
}
func (m *QueryAllTokenMigrationResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTokenMigrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTokenMigrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTokenMigrationResponse proto.InternalMessageInfo

func (m *QueryAllTokenMigrationResponse) GetTokenMigration() []TokenMigration {
	if m != nil {
		return m.TokenMigration
	}
	return nil
}

func (m *QueryAllTokenMigrationResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAclRequest struct {
}

func (m *QueryGetAclRequest) Reset()         { *m = QueryGetAclRequest{} }
func (m *QueryGetAclRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAclRequest) ProtoMessage()    {}
func (*QueryGetAclRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{6}
}
func (m *QueryGetAclRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAclRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAclRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAclRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAclRequest.Merge(m, src)
}
func (m *QueryGetAclRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAclRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAclRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAclRequest proto.InternalMessageInfo

type QueryGetAclResponse struct {
	Acl Acl `protobuf:"bytes,1,opt,name=Acl,proto3" json:"Acl"`
}

func (m *QueryGetAclResponse) Reset()         { *m = QueryGetAclResponse{} }
func (m *QueryGetAclResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAclResponse) ProtoMessage()    {}
func (*QueryGetAclResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{7}
}
func (m *QueryGetAclResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAclResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAclResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAclResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAclResponse.Merge(m, src)
}
func (m *QueryGetAclResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAclResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAclResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAclResponse proto.InternalMessageInfo

func (m *QueryGetAclResponse) GetAcl() Acl {
	if m != nil {
		return m.Acl
	}
	return Acl{}
}

type QueryGetMigratorRequest struct {
	Migrator string `protobuf:"bytes,1,opt,name=migrator,proto3" json:"migrator,omitempty"`
}

func (m *QueryGetMigratorRequest) Reset()         { *m = QueryGetMigratorRequest{} }
func (m *QueryGetMigratorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetMigratorRequest) ProtoMessage()    {}
func (*QueryGetMigratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{8}
}
func (m *QueryGetMigratorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMigratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMigratorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMigratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMigratorRequest.Merge(m, src)
}
func (m *QueryGetMigratorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMigratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMigratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMigratorRequest proto.InternalMessageInfo

func (m *QueryGetMigratorRequest) GetMigrator() string {
	if m != nil {
		return m.Migrator
	}
	return ""
}

type QueryGetMigratorResponse struct {
	Migrator Migrator `protobuf:"bytes,1,opt,name=migrator,proto3" json:"migrator"`
}

func (m *QueryGetMigratorResponse) Reset()         { *m = QueryGetMigratorResponse{} }
func (m *QueryGetMigratorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetMigratorResponse) ProtoMessage()    {}
func (*QueryGetMigratorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{9}
}
func (m *QueryGetMigratorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetMigratorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetMigratorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetMigratorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetMigratorResponse.Merge(m, src)
}
func (m *QueryGetMigratorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetMigratorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetMigratorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetMigratorResponse proto.InternalMessageInfo

func (m *QueryGetMigratorResponse) GetMigrator() Migrator {
	if m != nil {
		return m.Migrator
	}
	return Migrator{}
}

type QueryAllMigratorRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMigratorRequest) Reset()         { *m = QueryAllMigratorRequest{} }
func (m *QueryAllMigratorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMigratorRequest) ProtoMessage()    {}
func (*QueryAllMigratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{10}
}
func (m *QueryAllMigratorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMigratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMigratorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMigratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMigratorRequest.Merge(m, src)
}
func (m *QueryAllMigratorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMigratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMigratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMigratorRequest proto.InternalMessageInfo

func (m *QueryAllMigratorRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllMigratorResponse struct {
	Migrator   []Migrator          `protobuf:"bytes,1,rep,name=migrator,proto3" json:"migrator"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMigratorResponse) Reset()         { *m = QueryAllMigratorResponse{} }
func (m *QueryAllMigratorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMigratorResponse) ProtoMessage()    {}
func (*QueryAllMigratorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7ee2cef3f639714b, []int{11}
}
func (m *QueryAllMigratorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMigratorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMigratorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMigratorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMigratorResponse.Merge(m, src)
}
func (m *QueryAllMigratorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMigratorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMigratorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMigratorResponse proto.InternalMessageInfo

func (m *QueryAllMigratorResponse) GetMigrator() []Migrator {
	if m != nil {
		return m.Migrator
	}
	return nil
}

func (m *QueryAllMigratorResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "frontier.migration.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "frontier.migration.QueryParamsResponse")
	proto.RegisterType((*QueryGetTokenMigrationRequest)(nil), "frontier.migration.QueryGetTokenMigrationRequest")
	proto.RegisterType((*QueryGetTokenMigrationResponse)(nil), "frontier.migration.QueryGetTokenMigrationResponse")
	proto.RegisterType((*QueryAllTokenMigrationRequest)(nil), "frontier.migration.QueryAllTokenMigrationRequest")
	proto.RegisterType((*QueryAllTokenMigrationResponse)(nil), "frontier.migration.QueryAllTokenMigrationResponse")
	proto.RegisterType((*QueryGetAclRequest)(nil), "frontier.migration.QueryGetAclRequest")
	proto.RegisterType((*QueryGetAclResponse)(nil), "frontier.migration.QueryGetAclResponse")
	proto.RegisterType((*QueryGetMigratorRequest)(nil), "frontier.migration.QueryGetMigratorRequest")
	proto.RegisterType((*QueryGetMigratorResponse)(nil), "frontier.migration.QueryGetMigratorResponse")
	proto.RegisterType((*QueryAllMigratorRequest)(nil), "frontier.migration.QueryAllMigratorRequest")
	proto.RegisterType((*QueryAllMigratorResponse)(nil), "frontier.migration.QueryAllMigratorResponse")
}

func init() { proto.RegisterFile("frontier/migration/query.proto", fileDescriptor_7ee2cef3f639714b) }

var fileDescriptor_7ee2cef3f639714b = []byte{
	// 685 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4f, 0x6f, 0xd3, 0x3e,
	0x18, 0xc7, 0x9b, 0xed, 0xf7, 0xdb, 0x86, 0x27, 0x4d, 0xc2, 0x4c, 0xda, 0x88, 0x4a, 0x06, 0x06,
	0xb6, 0xc1, 0x20, 0x56, 0x0b, 0x93, 0xe0, 0x82, 0x94, 0x1d, 0x56, 0x2e, 0x13, 0xa5, 0xe2, 0xb4,
	0x0b, 0x72, 0x2b, 0x13, 0x2a, 0xd2, 0x38, 0x4b, 0x32, 0x60, 0x9a, 0x7a, 0x41, 0x9c, 0x11, 0x12,
	0x12, 0x6f, 0x80, 0x03, 0x37, 0xde, 0x00, 0x6f, 0x60, 0xc7, 0x49, 0x5c, 0x38, 0x21, 0xd4, 0xf2,
	0x42, 0x50, 0x9c, 0xc7, 0xdd, 0xd2, 0x3a, 0x69, 0x27, 0x76, 0x8b, 0xf3, 0xfc, 0xfb, 0xd8, 0xcf,
	0xd7, 0x8f, 0x91, 0xf5, 0x22, 0x14, 0x7e, 0xdc, 0xe6, 0x21, 0xed, 0xb4, 0xdd, 0x90, 0xc5, 0x6d,
	0xe1, 0xd3, 0xbd, 0x7d, 0x1e, 0x1e, 0xd8, 0x41, 0x28, 0x62, 0x81, 0xb1, 0xb2, 0xdb, 0x03, 0xbb,
	0xb9, 0xe8, 0x0a, 0x57, 0x48, 0x33, 0x4d, 0xbe, 0x52, 0x4f, 0xb3, 0xec, 0x0a, 0xe1, 0x7a, 0x9c,
	0xb2, 0xa0, 0x4d, 0x99, 0xef, 0x8b, 0x58, 0x3a, 0x47, 0x60, 0xbd, 0xdd, 0x12, 0x51, 0x47, 0x44,
	0xb4, 0xc9, 0x22, 0x9e, 0x16, 0xa0, 0xaf, 0x2b, 0x4d, 0x1e, 0xb3, 0x0a, 0x0d, 0x98, 0xdb, 0xf6,
	0xa5, 0x33, 0xf8, 0xae, 0x68, 0x98, 0x02, 0x16, 0xb2, 0x8e, 0x4a, 0xb6, 0xae, 0x71, 0x88, 0xc5,
	0x2b, 0xee, 0x3f, 0x1f, 0xac, 0x15, 0x94, 0xc6, 0x93, 0xb5, 0x3c, 0xb0, 0x5e, 0xd3, 0x58, 0xd3,
	0x2f, 0x11, 0xa6, 0x2e, 0x64, 0x11, 0xe1, 0xa7, 0x09, 0x6d, 0x5d, 0xd6, 0x6f, 0xf0, 0xbd, 0x7d,
	0x1e, 0xc5, 0xe4, 0x09, 0xba, 0x94, 0xf9, 0x1b, 0x05, 0xc2, 0x8f, 0x38, 0x7e, 0x80, 0x66, 0x52,
	0xce, 0x65, 0xe3, 0xaa, 0xb1, 0x3e, 0x5f, 0x35, 0xed, 0xd1, 0xd3, 0xb3, 0xd3, 0x98, 0xad, 0xff,
	0x8e, 0x7e, 0xad, 0x94, 0x1a, 0xe0, 0x4f, 0x1e, 0xa2, 0x2b, 0x32, 0x61, 0x8d, 0xc7, 0xcf, 0x92,
	0x8d, 0xec, 0x28, 0x77, 0xa8, 0x88, 0x97, 0xd1, 0x6c, 0x27, 0x72, 0x1f, 0xb3, 0xe8, 0xa5, 0xcc,
	0x7d, 0xa1, 0xa1, 0x96, 0x24, 0x44, 0x56, 0x5e, 0x28, 0x60, 0xd5, 0xd1, 0x42, 0x9c, 0xb1, 0x00,
	0x1e, 0xd1, 0xe1, 0x65, 0x73, 0x00, 0xe6, 0x50, 0x3c, 0x71, 0x01, 0xd7, 0xf1, 0x3c, 0x3d, 0xee,
	0x36, 0x42, 0x27, 0x6d, 0x85, 0x72, 0xab, 0x76, 0xaa, 0x01, 0x3b, 0xd1, 0x80, 0x9d, 0x8a, 0x0c,
	0x34, 0x60, 0xd7, 0x99, 0xcb, 0x21, 0xb6, 0x71, 0x2a, 0x92, 0x7c, 0x37, 0x60, 0x77, 0x9a, 0x4a,
	0x05, 0xbb, 0x9b, 0xfe, 0x97, 0xdd, 0xe1, 0x5a, 0x06, 0x7e, 0x4a, 0xc2, 0xaf, 0x8d, 0x85, 0x4f,
	0x71, 0x32, 0xf4, 0x4a, 0x3c, 0x35, 0x1e, 0x3b, 0x2d, 0x4f, 0x89, 0x67, 0x1b, 0xc4, 0xa3, 0xfe,
	0xc2, 0x3e, 0x28, 0x9a, 0x76, 0x5a, 0x1e, 0x9c, 0xd5, 0x92, 0x0e, 0xde, 0x69, 0x79, 0x40, 0x9c,
	0x78, 0x92, 0x4d, 0xb4, 0xa4, 0xf2, 0xec, 0x80, 0x68, 0xd5, 0xf1, 0x9b, 0x68, 0x4e, 0xe9, 0x18,
	0xe4, 0x32, 0x58, 0x93, 0x5d, 0xb4, 0x3c, 0x1a, 0x06, 0x0c, 0x8f, 0x86, 0xe2, 0xe6, 0xab, 0x65,
	0x1d, 0x88, 0x8a, 0x03, 0x9a, 0x93, 0xdc, 0x0c, 0x90, 0x1c, 0xcf, 0x1b, 0x46, 0x3a, 0x2f, 0x45,
	0x7c, 0x31, 0x80, 0x3f, 0x53, 0x43, 0xcb, 0x3f, 0x7d, 0x56, 0xfe, 0x73, 0xeb, 0x7c, 0xf5, 0xfd,
	0x2c, 0xfa, 0x5f, 0x52, 0xe2, 0x2e, 0x9a, 0x49, 0x6f, 0x3c, 0x5e, 0xd5, 0xa1, 0x8c, 0x0e, 0x17,
	0x73, 0x6d, 0xac, 0x5f, 0x5a, 0x90, 0x90, 0x77, 0x3f, 0xfe, 0x7c, 0x9a, 0x2a, 0x63, 0x93, 0xe6,
	0x0e, 0x4c, 0xfc, 0xcd, 0x40, 0x0b, 0x59, 0xd1, 0xe3, 0x4a, 0x6e, 0xfe, 0xbc, 0xe9, 0x63, 0x56,
	0xcf, 0x12, 0x02, 0x74, 0x9b, 0x92, 0x8e, 0xe2, 0xbb, 0x74, 0xfc, 0xb4, 0xa6, 0x87, 0x30, 0xcd,
	0xba, 0xf8, 0xab, 0x81, 0x2e, 0x66, 0x33, 0x3a, 0x9e, 0x57, 0xc0, 0x9c, 0x37, 0x82, 0x0a, 0x98,
	0x73, 0x67, 0x09, 0xd9, 0x90, 0xcc, 0x37, 0xf1, 0xf5, 0x09, 0x98, 0xf1, 0x1b, 0x79, 0x61, 0x0b,
	0xda, 0x9a, 0xb9, 0xf6, 0x05, 0x6d, 0xcd, 0x0e, 0x02, 0xb2, 0x22, 0x21, 0x2e, 0xe3, 0x25, 0xaa,
	0x7f, 0xbc, 0xf0, 0x67, 0x03, 0xcd, 0x29, 0x09, 0xe3, 0x8d, 0xa2, 0xb4, 0x43, 0x97, 0xd0, 0xbc,
	0x33, 0x99, 0x33, 0x80, 0x50, 0x09, 0x72, 0x0b, 0xaf, 0xd1, 0x82, 0x77, 0x92, 0x1e, 0xaa, 0xaf,
	0x2e, 0xfe, 0x60, 0xa0, 0x79, 0x95, 0x25, 0xe9, 0xda, 0x46, 0x51, 0x0b, 0x26, 0x67, 0xd3, 0xdc,
	0x74, 0x72, 0x43, 0xb2, 0x59, 0xb8, 0x5c, 0xc4, 0xb6, 0x75, 0xff, 0xa8, 0x67, 0x19, 0xc7, 0x3d,
	0xcb, 0xf8, 0xdd, 0xb3, 0x8c, 0x8f, 0x7d, 0xab, 0x74, 0xdc, 0xb7, 0x4a, 0x3f, 0xfb, 0x56, 0x69,
	0xd7, 0x1c, 0x84, 0xbd, 0x3d, 0xdd, 0xe2, 0x83, 0x80, 0x47, 0xcd, 0x19, 0xf9, 0xf4, 0xdf, 0xfb,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xfb, 0xcb, 0x78, 0x1c, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of TokenMigration items.
	TokenMigration(ctx context.Context, in *QueryGetTokenMigrationRequest, opts ...grpc.CallOption) (*QueryGetTokenMigrationResponse, error)
	TokenMigrationAll(ctx context.Context, in *QueryAllTokenMigrationRequest, opts ...grpc.CallOption) (*QueryAllTokenMigrationResponse, error)
	// Queries a Acl by index.
	Acl(ctx context.Context, in *QueryGetAclRequest, opts ...grpc.CallOption) (*QueryGetAclResponse, error)
	// Queries a list of Migrator items.
	Migrator(ctx context.Context, in *QueryGetMigratorRequest, opts ...grpc.CallOption) (*QueryGetMigratorResponse, error)
	MigratorAll(ctx context.Context, in *QueryAllMigratorRequest, opts ...grpc.CallOption) (*QueryAllMigratorResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/frontier.migration.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TokenMigration(ctx context.Context, in *QueryGetTokenMigrationRequest, opts ...grpc.CallOption) (*QueryGetTokenMigrationResponse, error) {
	out := new(QueryGetTokenMigrationResponse)
	err := c.cc.Invoke(ctx, "/frontier.migration.Query/TokenMigration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TokenMigrationAll(ctx context.Context, in *QueryAllTokenMigrationRequest, opts ...grpc.CallOption) (*QueryAllTokenMigrationResponse, error) {
	out := new(QueryAllTokenMigrationResponse)
	err := c.cc.Invoke(ctx, "/frontier.migration.Query/TokenMigrationAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Acl(ctx context.Context, in *QueryGetAclRequest, opts ...grpc.CallOption) (*QueryGetAclResponse, error) {
	out := new(QueryGetAclResponse)
	err := c.cc.Invoke(ctx, "/frontier.migration.Query/Acl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Migrator(ctx context.Context, in *QueryGetMigratorRequest, opts ...grpc.CallOption) (*QueryGetMigratorResponse, error) {
	out := new(QueryGetMigratorResponse)
	err := c.cc.Invoke(ctx, "/frontier.migration.Query/Migrator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MigratorAll(ctx context.Context, in *QueryAllMigratorRequest, opts ...grpc.CallOption) (*QueryAllMigratorResponse, error) {
	out := new(QueryAllMigratorResponse)
	err := c.cc.Invoke(ctx, "/frontier.migration.Query/MigratorAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of TokenMigration items.
	TokenMigration(context.Context, *QueryGetTokenMigrationRequest) (*QueryGetTokenMigrationResponse, error)
	TokenMigrationAll(context.Context, *QueryAllTokenMigrationRequest) (*QueryAllTokenMigrationResponse, error)
	// Queries a Acl by index.
	Acl(context.Context, *QueryGetAclRequest) (*QueryGetAclResponse, error)
	// Queries a list of Migrator items.
	Migrator(context.Context, *QueryGetMigratorRequest) (*QueryGetMigratorResponse, error)
	MigratorAll(context.Context, *QueryAllMigratorRequest) (*QueryAllMigratorResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) TokenMigration(ctx context.Context, req *QueryGetTokenMigrationRequest) (*QueryGetTokenMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenMigration not implemented")
}
func (*UnimplementedQueryServer) TokenMigrationAll(ctx context.Context, req *QueryAllTokenMigrationRequest) (*QueryAllTokenMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenMigrationAll not implemented")
}
func (*UnimplementedQueryServer) Acl(ctx context.Context, req *QueryGetAclRequest) (*QueryGetAclResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Acl not implemented")
}
func (*UnimplementedQueryServer) Migrator(ctx context.Context, req *QueryGetMigratorRequest) (*QueryGetMigratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrator not implemented")
}
func (*UnimplementedQueryServer) MigratorAll(ctx context.Context, req *QueryAllMigratorRequest) (*QueryAllMigratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigratorAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontier.migration.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TokenMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTokenMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TokenMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontier.migration.Query/TokenMigration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TokenMigration(ctx, req.(*QueryGetTokenMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TokenMigrationAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTokenMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TokenMigrationAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontier.migration.Query/TokenMigrationAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TokenMigrationAll(ctx, req.(*QueryAllTokenMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Acl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Acl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontier.migration.Query/Acl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Acl(ctx, req.(*QueryGetAclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Migrator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetMigratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Migrator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontier.migration.Query/Migrator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Migrator(ctx, req.(*QueryGetMigratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MigratorAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMigratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MigratorAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/frontier.migration.Query/MigratorAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MigratorAll(ctx, req.(*QueryAllMigratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "frontier.migration.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "TokenMigration",
			Handler:    _Query_TokenMigration_Handler,
		},
		{
			MethodName: "TokenMigrationAll",
			Handler:    _Query_TokenMigrationAll_Handler,
		},
		{
			MethodName: "Acl",
			Handler:    _Query_Acl_Handler,
		},
		{
			MethodName: "Migrator",
			Handler:    _Query_Migrator_Handler,
		},
		{
			MethodName: "MigratorAll",
			Handler:    _Query_MigratorAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontier/migration/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetTokenMigrationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTokenMigrationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTokenMigrationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MsgHash) > 0 {
		i -= len(m.MsgHash)
		copy(dAtA[i:], m.MsgHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MsgHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTokenMigrationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTokenMigrationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTokenMigrationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TokenMigration.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllTokenMigrationRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTokenMigrationRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTokenMigrationRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTokenMigrationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTokenMigrationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTokenMigrationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.TokenMigration) > 0 {
		for iNdEx := len(m.TokenMigration) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenMigration[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAclRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAclRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAclRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetAclResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAclResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAclResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Acl.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetMigratorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMigratorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMigratorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Migrator) > 0 {
		i -= len(m.Migrator)
		copy(dAtA[i:], m.Migrator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Migrator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetMigratorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetMigratorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetMigratorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Migrator.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllMigratorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMigratorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMigratorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMigratorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMigratorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMigratorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Migrator) > 0 {
		for iNdEx := len(m.Migrator) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Migrator[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetTokenMigrationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MsgHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTokenMigrationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TokenMigration.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllTokenMigrationRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTokenMigrationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TokenMigration) > 0 {
		for _, e := range m.TokenMigration {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAclRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetAclResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Acl.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetMigratorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Migrator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetMigratorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Migrator.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllMigratorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMigratorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Migrator) > 0 {
		for _, e := range m.Migrator {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTokenMigrationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTokenMigrationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTokenMigrationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MsgHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTokenMigrationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTokenMigrationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTokenMigrationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenMigration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenMigration.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTokenMigrationRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTokenMigrationRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTokenMigrationRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTokenMigrationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTokenMigrationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTokenMigrationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenMigration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenMigration = append(m.TokenMigration, TokenMigration{})
			if err := m.TokenMigration[len(m.TokenMigration)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAclRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAclRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAclRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAclResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAclResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAclResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Acl", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Acl.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMigratorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMigratorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMigratorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Migrator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Migrator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetMigratorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetMigratorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetMigratorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Migrator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Migrator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMigratorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMigratorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMigratorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMigratorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMigratorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMigratorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Migrator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Migrator = append(m.Migrator, Migrator{})
			if err := m.Migrator[len(m.Migrator)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
