FROM --platform=linux ubuntu:22.04
ARG BUILDARCH

ENV LOCAL=/usr/local

COPY build/cosmovisor ${LOCAL}/bin/cosmovisor

ENV DAEMON_NAME frontierd
ENV DAEMON_HOME /root/.frontier
ENV DAEMON_RESTART_AFTER_UPGRADE false

# Create the folder for the genesis binary and copy the frontierd binary:
RUN mkdir -p ${DAEMON_HOME}/cosmovisor/genesis/bin
COPY build/frontierd-linux-${BUILDARCH} ${DAEMON_HOME}/cosmovisor/genesis/bin

ENTRYPOINT ["cosmovisor", "run", "start"]

# Create the image
# $ docker build -f Dockerfile-ubuntu-prod . -t frontd_i:v1
# To test only 1 command
# $ docker run --rm -it frontd_i:v1
# To build container
# $ docker create --name frontd -i -v $(pwd)/docker/val-alice:/root/.checkers frontd_i:v1
# $ docker start frontd
# To run server on it
# $ docker exec -it frontd start
# In other shell, to query it
# $ docker exec -it frontd version
