version: "3.7"

networks:
  net-alice-kms:
  net-alice:
  net-bob:
  net-public:

services:
  kms-alice:
    command: start --config /root/tmkms/tmkms.toml
    container_name: kms-alice
    image: tmkms_i:v0.12.2
    volumes:
      - ./docker/kms-alice:/root/tmkms
    networks:
      - net-alice-kms

  val-alice:
    command: start
    container_name: val-alice
    image: frontd_i
    volumes:
      - ./docker/val-alice:/root/.front
    networks:
      - net-alice-kms
      - net-alice
    # The KMS connects to the node and can reconnect. So have val-alice start after kms-alice:
    depends_on:
      - kms-alice

  sentry-alice:
    command: start
    container_name: sentry-alice
    image: frontd_i
    volumes:
       - ./docker/sentry-alice:/root/.front
    networks:
      - net-alice
      - net-public

  val-bob:
    command: start
    container_name: val-bob
    image: frontd_i
    volumes:
      - ./docker/val-bob:/root/.front
    networks:
      - net-bob

  sentry-bob:
    command: start
    container_name: sentry-bob
    image: frontd_i
    volumes:
      - ./docker/sentry-bob:/root/.front
    networks:
      - net-bob
      - net-public

  node-carol:
    command: start
    container_name: node-carol
    image: frontd_i
    # In order to make your host computer look like an open node, expose Carol's node on all addresses of your host
    ports:
      - 0.0.0.0:26657:26657
      - 0.0.0.0:1317:1317
    volumes:
      - ./docker/node-carol:/root/.front
    networks:
      - net-public
      
  val-ppoliani:
    command: start
    container_name: val-ppoliani
    image: frontd_i
    ports:
      - 0.0.0.0:26658:26657
      - 0.0.0.0:1318:1317
    volumes:
      - ./docker/val-ppoliani:/root/.front
    networks:
      - net-public
