FROM --platform=linux ubuntu:22.04
ARG BUILDARCH

ENV LOCAL=/usr/local

COPY build/cosmovisor ${LOCAL}/bin/cosmovisor
COPY build/selfchaind-linux-${BUILDARCH} ${LOCAL}/bin/selfchaind

ENTRYPOINT ["cosmovisor"]
