# Tendermint KMS configuration file

## Chain Configuration

### Cosmos Hub Network

[[chain]]
id = "frontier-1"
key_format = { type = "bech32", account_key_prefix = "frontpub", consensus_key_prefix = "frontvalconspub" }
state_file = "/root/tmkms/state/frontier-1-consensus.json"

## Signing Provider Configuration

### Software-based Signer Configuration

[[providers.softsign]]
chain_ids = ["frontier-1"]
key_type = "consensus"
path = "/root/tmkms/secrets/val-alice-consensus.key"

## Validator Configuration

[[validator]]
chain_id = "frontier-1"
addr = "tcp://val-alice:26659"
secret_key = "/root/tmkms/secrets/kms-identity.key"
protocol_version = "v0.34"
reconnect = true

