// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: selfchain/identity/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryDIDDocumentRequest is request type for the Query/DIDDocument method.
type QueryDIDDocumentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryDIDDocumentRequest) Reset()         { *m = QueryDIDDocumentRequest{} }
func (m *QueryDIDDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDIDDocumentRequest) ProtoMessage()    {}
func (*QueryDIDDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{2}
}
func (m *QueryDIDDocumentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDIDDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDIDDocumentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDIDDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDIDDocumentRequest.Merge(m, src)
}
func (m *QueryDIDDocumentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDIDDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDIDDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDIDDocumentRequest proto.InternalMessageInfo

func (m *QueryDIDDocumentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryDIDDocumentResponse is response type for the Query/DIDDocument method.
type QueryDIDDocumentResponse struct {
	Document DIDDocument `protobuf:"bytes,1,opt,name=document,proto3" json:"document"`
}

func (m *QueryDIDDocumentResponse) Reset()         { *m = QueryDIDDocumentResponse{} }
func (m *QueryDIDDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDIDDocumentResponse) ProtoMessage()    {}
func (*QueryDIDDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{3}
}
func (m *QueryDIDDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDIDDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDIDDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDIDDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDIDDocumentResponse.Merge(m, src)
}
func (m *QueryDIDDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDIDDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDIDDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDIDDocumentResponse proto.InternalMessageInfo

func (m *QueryDIDDocumentResponse) GetDocument() DIDDocument {
	if m != nil {
		return m.Document
	}
	return DIDDocument{}
}

// QueryCredentialRequest is request type for the Query/Credential method.
type QueryCredentialRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryCredentialRequest) Reset()         { *m = QueryCredentialRequest{} }
func (m *QueryCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCredentialRequest) ProtoMessage()    {}
func (*QueryCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{4}
}
func (m *QueryCredentialRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCredentialRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCredentialRequest.Merge(m, src)
}
func (m *QueryCredentialRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCredentialRequest proto.InternalMessageInfo

func (m *QueryCredentialRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryCredentialResponse is response type for the Query/Credential method.
type QueryCredentialResponse struct {
	Credential Credential `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential"`
}

func (m *QueryCredentialResponse) Reset()         { *m = QueryCredentialResponse{} }
func (m *QueryCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCredentialResponse) ProtoMessage()    {}
func (*QueryCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{5}
}
func (m *QueryCredentialResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCredentialResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCredentialResponse.Merge(m, src)
}
func (m *QueryCredentialResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCredentialResponse proto.InternalMessageInfo

func (m *QueryCredentialResponse) GetCredential() Credential {
	if m != nil {
		return m.Credential
	}
	return Credential{}
}

// QueryVerifyCredentialRequest is request type for the Query/VerifyCredential method.
type QueryVerifyCredentialRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryVerifyCredentialRequest) Reset()         { *m = QueryVerifyCredentialRequest{} }
func (m *QueryVerifyCredentialRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVerifyCredentialRequest) ProtoMessage()    {}
func (*QueryVerifyCredentialRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{6}
}
func (m *QueryVerifyCredentialRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifyCredentialRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifyCredentialRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifyCredentialRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifyCredentialRequest.Merge(m, src)
}
func (m *QueryVerifyCredentialRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifyCredentialRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifyCredentialRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifyCredentialRequest proto.InternalMessageInfo

func (m *QueryVerifyCredentialRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryVerifyCredentialResponse is response type for the Query/VerifyCredential method.
type QueryVerifyCredentialResponse struct {
	Status VerificationStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
}

func (m *QueryVerifyCredentialResponse) Reset()         { *m = QueryVerifyCredentialResponse{} }
func (m *QueryVerifyCredentialResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVerifyCredentialResponse) ProtoMessage()    {}
func (*QueryVerifyCredentialResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{7}
}
func (m *QueryVerifyCredentialResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVerifyCredentialResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVerifyCredentialResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVerifyCredentialResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVerifyCredentialResponse.Merge(m, src)
}
func (m *QueryVerifyCredentialResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVerifyCredentialResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVerifyCredentialResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVerifyCredentialResponse proto.InternalMessageInfo

func (m *QueryVerifyCredentialResponse) GetStatus() VerificationStatus {
	if m != nil {
		return m.Status
	}
	return VerificationStatus{}
}

// VerificationStatus represents the verification status of a credential.
type VerificationStatus struct {
	Valid  bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *VerificationStatus) Reset()         { *m = VerificationStatus{} }
func (m *VerificationStatus) String() string { return proto.CompactTextString(m) }
func (*VerificationStatus) ProtoMessage()    {}
func (*VerificationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{8}
}
func (m *VerificationStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerificationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerificationStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerificationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationStatus.Merge(m, src)
}
func (m *VerificationStatus) XXX_Size() int {
	return m.Size()
}
func (m *VerificationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationStatus proto.InternalMessageInfo

func (m *VerificationStatus) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *VerificationStatus) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// QueryMFAConfigRequest is request type for the Query/MFAConfig method.
type QueryMFAConfigRequest struct {
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (m *QueryMFAConfigRequest) Reset()         { *m = QueryMFAConfigRequest{} }
func (m *QueryMFAConfigRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMFAConfigRequest) ProtoMessage()    {}
func (*QueryMFAConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{9}
}
func (m *QueryMFAConfigRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMFAConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMFAConfigRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMFAConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMFAConfigRequest.Merge(m, src)
}
func (m *QueryMFAConfigRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMFAConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMFAConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMFAConfigRequest proto.InternalMessageInfo

func (m *QueryMFAConfigRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

// QueryMFAConfigResponse is response type for the Query/MFAConfig method.
type QueryMFAConfigResponse struct {
	Config MFAConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config"`
}

func (m *QueryMFAConfigResponse) Reset()         { *m = QueryMFAConfigResponse{} }
func (m *QueryMFAConfigResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMFAConfigResponse) ProtoMessage()    {}
func (*QueryMFAConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{10}
}
func (m *QueryMFAConfigResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMFAConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMFAConfigResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMFAConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMFAConfigResponse.Merge(m, src)
}
func (m *QueryMFAConfigResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMFAConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMFAConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMFAConfigResponse proto.InternalMessageInfo

func (m *QueryMFAConfigResponse) GetConfig() MFAConfig {
	if m != nil {
		return m.Config
	}
	return MFAConfig{}
}

// QueryMFAChallengeRequest is request type for the Query/MFAChallenge method.
type QueryMFAChallengeRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryMFAChallengeRequest) Reset()         { *m = QueryMFAChallengeRequest{} }
func (m *QueryMFAChallengeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMFAChallengeRequest) ProtoMessage()    {}
func (*QueryMFAChallengeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{11}
}
func (m *QueryMFAChallengeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMFAChallengeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMFAChallengeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMFAChallengeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMFAChallengeRequest.Merge(m, src)
}
func (m *QueryMFAChallengeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMFAChallengeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMFAChallengeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMFAChallengeRequest proto.InternalMessageInfo

func (m *QueryMFAChallengeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryMFAChallengeResponse is response type for the Query/MFAChallenge method.
type QueryMFAChallengeResponse struct {
	Challenge MFAChallenge `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge"`
}

func (m *QueryMFAChallengeResponse) Reset()         { *m = QueryMFAChallengeResponse{} }
func (m *QueryMFAChallengeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMFAChallengeResponse) ProtoMessage()    {}
func (*QueryMFAChallengeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{12}
}
func (m *QueryMFAChallengeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMFAChallengeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMFAChallengeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMFAChallengeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMFAChallengeResponse.Merge(m, src)
}
func (m *QueryMFAChallengeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMFAChallengeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMFAChallengeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMFAChallengeResponse proto.InternalMessageInfo

func (m *QueryMFAChallengeResponse) GetChallenge() MFAChallenge {
	if m != nil {
		return m.Challenge
	}
	return MFAChallenge{}
}

// QueryRecoverySessionRequest is request type for the Query/RecoverySession method.
type QueryRecoverySessionRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryRecoverySessionRequest) Reset()         { *m = QueryRecoverySessionRequest{} }
func (m *QueryRecoverySessionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecoverySessionRequest) ProtoMessage()    {}
func (*QueryRecoverySessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{13}
}
func (m *QueryRecoverySessionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoverySessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoverySessionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoverySessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoverySessionRequest.Merge(m, src)
}
func (m *QueryRecoverySessionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoverySessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoverySessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoverySessionRequest proto.InternalMessageInfo

func (m *QueryRecoverySessionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryRecoverySessionResponse is response type for the Query/RecoverySession method.
type QueryRecoverySessionResponse struct {
	Session RecoverySession `protobuf:"bytes,1,opt,name=session,proto3" json:"session"`
}

func (m *QueryRecoverySessionResponse) Reset()         { *m = QueryRecoverySessionResponse{} }
func (m *QueryRecoverySessionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRecoverySessionResponse) ProtoMessage()    {}
func (*QueryRecoverySessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7023bccf898bb2a2, []int{14}
}
func (m *QueryRecoverySessionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRecoverySessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRecoverySessionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRecoverySessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecoverySessionResponse.Merge(m, src)
}
func (m *QueryRecoverySessionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRecoverySessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecoverySessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecoverySessionResponse proto.InternalMessageInfo

func (m *QueryRecoverySessionResponse) GetSession() RecoverySession {
	if m != nil {
		return m.Session
	}
	return RecoverySession{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "selfchain.identity.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "selfchain.identity.QueryParamsResponse")
	proto.RegisterType((*QueryDIDDocumentRequest)(nil), "selfchain.identity.QueryDIDDocumentRequest")
	proto.RegisterType((*QueryDIDDocumentResponse)(nil), "selfchain.identity.QueryDIDDocumentResponse")
	proto.RegisterType((*QueryCredentialRequest)(nil), "selfchain.identity.QueryCredentialRequest")
	proto.RegisterType((*QueryCredentialResponse)(nil), "selfchain.identity.QueryCredentialResponse")
	proto.RegisterType((*QueryVerifyCredentialRequest)(nil), "selfchain.identity.QueryVerifyCredentialRequest")
	proto.RegisterType((*QueryVerifyCredentialResponse)(nil), "selfchain.identity.QueryVerifyCredentialResponse")
	proto.RegisterType((*VerificationStatus)(nil), "selfchain.identity.VerificationStatus")
	proto.RegisterType((*QueryMFAConfigRequest)(nil), "selfchain.identity.QueryMFAConfigRequest")
	proto.RegisterType((*QueryMFAConfigResponse)(nil), "selfchain.identity.QueryMFAConfigResponse")
	proto.RegisterType((*QueryMFAChallengeRequest)(nil), "selfchain.identity.QueryMFAChallengeRequest")
	proto.RegisterType((*QueryMFAChallengeResponse)(nil), "selfchain.identity.QueryMFAChallengeResponse")
	proto.RegisterType((*QueryRecoverySessionRequest)(nil), "selfchain.identity.QueryRecoverySessionRequest")
	proto.RegisterType((*QueryRecoverySessionResponse)(nil), "selfchain.identity.QueryRecoverySessionResponse")
}

func init() { proto.RegisterFile("selfchain/identity/query.proto", fileDescriptor_7023bccf898bb2a2) }

var fileDescriptor_7023bccf898bb2a2 = []byte{
	// 873 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0x4d, 0x6f, 0xfb, 0x44,
	0x10, 0xc6, 0xe3, 0xc0, 0x3f, 0x34, 0x53, 0x54, 0xaa, 0xa5, 0x94, 0x62, 0x52, 0xb7, 0xb8, 0x2f,
	0x34, 0x2f, 0xcd, 0xf6, 0x85, 0x43, 0x05, 0x17, 0xda, 0x46, 0x48, 0x95, 0x40, 0x40, 0x2a, 0x38,
	0x20, 0xa1, 0xca, 0xd8, 0x9b, 0x74, 0x85, 0xeb, 0x4d, 0x6d, 0x27, 0xa2, 0x8a, 0x72, 0x41, 0xe2,
	0x8a, 0x2a, 0x38, 0x72, 0x45, 0x70, 0xe0, 0x8b, 0xf4, 0x58, 0x89, 0x0b, 0x27, 0x84, 0x5a, 0x3e,
	0x08, 0xca, 0x7a, 0xec, 0xa4, 0xf1, 0x3a, 0x0d, 0x37, 0xc7, 0xf3, 0x3c, 0x3b, 0xbf, 0x99, 0xdd,
	0x9d, 0x18, 0x8c, 0x80, 0xb9, 0x2d, 0xfb, 0xd2, 0xe2, 0x1e, 0xe5, 0x0e, 0xf3, 0x42, 0x1e, 0xde,
	0xd0, 0xeb, 0x2e, 0xf3, 0x6f, 0xea, 0x1d, 0x5f, 0x84, 0x82, 0x90, 0x24, 0x5e, 0x8f, 0xe3, 0xfa,
	0x52, 0x5b, 0xb4, 0x85, 0x0c, 0xd3, 0xe1, 0x53, 0xa4, 0xd4, 0x4b, 0x6d, 0x21, 0xda, 0x2e, 0xa3,
	0x56, 0x87, 0x53, 0xcb, 0xf3, 0x44, 0x68, 0x85, 0x5c, 0x78, 0x01, 0x46, 0xd7, 0x14, 0x79, 0x3a,
	0x96, 0x6f, 0x5d, 0xc5, 0x82, 0x2d, 0x85, 0xc0, 0xe1, 0xce, 0x85, 0x23, 0xec, 0xee, 0x15, 0xf3,
	0x42, 0x94, 0x6d, 0x28, 0x64, 0xb6, 0xcf, 0xe4, 0xa3, 0xe5, 0xa2, 0x48, 0x55, 0x94, 0xb0, 0xba,
	0xe1, 0x65, 0x8c, 0xaa, 0x88, 0x5f, 0xb5, 0x2c, 0x8c, 0xbe, 0xa3, 0x88, 0xfa, 0xcc, 0x16, 0xbd,
	0xa4, 0x2b, 0xe6, 0x12, 0x90, 0xcf, 0x87, 0x4d, 0xfa, 0x4c, 0x56, 0xd0, 0x64, 0xd7, 0x5d, 0x16,
	0x84, 0xe6, 0xa7, 0xf0, 0xfa, 0x93, 0xb7, 0x41, 0x47, 0x78, 0x01, 0x23, 0x47, 0x50, 0x88, 0x2a,
	0x5d, 0xd1, 0xd6, 0xb5, 0x9d, 0xf9, 0x03, 0xbd, 0x9e, 0xee, 0x69, 0x3d, 0xf2, 0x9c, 0xbc, 0x7c,
	0xf7, 0xf7, 0x5a, 0xae, 0x89, 0x7a, 0xb3, 0x0c, 0x6f, 0xca, 0x05, 0x1b, 0x67, 0x8d, 0x06, 0xb6,
	0x01, 0x73, 0x91, 0x05, 0xc8, 0x73, 0x47, 0x2e, 0x58, 0x6c, 0xe6, 0xb9, 0x63, 0x7e, 0x0d, 0x2b,
	0x69, 0x29, 0x02, 0x1c, 0xc3, 0x5c, 0xdc, 0x45, 0x44, 0x58, 0x53, 0x21, 0x8c, 0x59, 0x91, 0x23,
	0xb1, 0x99, 0x3b, 0xb0, 0x2c, 0x97, 0x3f, 0x4d, 0x5a, 0x9d, 0x05, 0x72, 0x81, 0xcc, 0xe3, 0x4a,
	0xe4, 0x68, 0x00, 0x8c, 0xb6, 0x0a, 0x49, 0x0c, 0x15, 0xc9, 0xc8, 0x8b, 0x20, 0x63, 0x3e, 0xb3,
	0x0e, 0x25, 0x99, 0xe0, 0x4b, 0xe6, 0xf3, 0xd6, 0x0c, 0x40, 0x0c, 0x56, 0x33, 0xf4, 0x09, 0x56,
	0x21, 0x08, 0xad, 0xb0, 0x1b, 0xef, 0xcf, 0xb6, 0x0a, 0x49, 0xba, 0xb9, 0x2d, 0xcf, 0xf4, 0xb9,
	0x54, 0xc7, 0x7b, 0x15, 0x79, 0xcd, 0x13, 0x20, 0x69, 0x0d, 0x59, 0x82, 0x17, 0x3d, 0xcb, 0x45,
	0x9e, 0xb9, 0x66, 0xf4, 0x83, 0x2c, 0x43, 0xc1, 0x67, 0x56, 0x20, 0xbc, 0x95, 0xbc, 0xc4, 0xc4,
	0x5f, 0x66, 0x19, 0xde, 0x90, 0xa8, 0x9f, 0x7c, 0x74, 0x7c, 0x2a, 0xbc, 0x16, 0x6f, 0xc7, 0x35,
	0x2d, 0xc2, 0x4b, 0x4e, 0x52, 0xd4, 0xf0, 0xd1, 0xfc, 0x02, 0x37, 0x64, 0x4c, 0x8a, 0xe5, 0x7c,
	0x00, 0x05, 0x5b, 0xbe, 0xc1, 0x72, 0x56, 0x55, 0xe5, 0x24, 0xb6, 0xb8, 0x8a, 0xc8, 0x62, 0x56,
	0xf0, 0x18, 0x0d, 0xe3, 0x97, 0x96, 0xeb, 0x32, 0xaf, 0xcd, 0xb2, 0x1a, 0x6b, 0xc1, 0x5b, 0x0a,
	0x6d, 0xd2, 0xd4, 0xa2, 0x1d, 0xbf, 0x44, 0x90, 0xf5, 0x2c, 0x90, 0x58, 0x87, 0x2c, 0x23, 0xa3,
	0xb9, 0x0b, 0x6f, 0xcb, 0x14, 0x4d, 0xbc, 0x7e, 0xe7, 0x2c, 0x08, 0xb8, 0xf0, 0xb2, 0x88, 0x6c,
	0x3c, 0x1a, 0x29, 0x39, 0x42, 0x9d, 0xc2, 0x2b, 0x41, 0xf4, 0x0a, 0x91, 0x36, 0x54, 0x48, 0x13,
	0x6e, 0xa4, 0x8a, 0x9d, 0x07, 0x3f, 0xcc, 0xc3, 0x0b, 0x99, 0x85, 0x0c, 0xa0, 0x10, 0x5d, 0x5b,
	0xa2, 0x3c, 0x32, 0xe9, 0x09, 0xa1, 0xbf, 0xfb, 0xac, 0x2e, 0x22, 0x35, 0xcd, 0xef, 0xff, 0xfc,
	0xf7, 0xe7, 0x7c, 0x89, 0xe8, 0x34, 0x73, 0x6e, 0x92, 0x1f, 0x35, 0x98, 0x1f, 0xbb, 0xb3, 0xa4,
	0x9a, 0xb9, 0x78, 0x7a, 0x7e, 0xe8, 0xb5, 0xd9, 0xc4, 0x88, 0xb3, 0x29, 0x71, 0x0c, 0x52, 0xa2,
	0xea, 0x29, 0x4d, 0xfb, 0xdc, 0x19, 0x90, 0x9f, 0x34, 0x80, 0xd1, 0xfd, 0x22, 0x95, 0xcc, 0x14,
	0xa9, 0x4b, 0xab, 0x57, 0x67, 0xd2, 0x22, 0x4d, 0x55, 0xd2, 0x6c, 0x91, 0x0d, 0x3a, 0xf5, 0xcf,
	0x20, 0x82, 0xfa, 0x4d, 0x83, 0x85, 0x73, 0x61, 0x73, 0xcb, 0x3d, 0x43, 0x09, 0xa9, 0x67, 0x26,
	0x7b, 0x2a, 0x8c, 0xe1, 0xe8, 0xcc, 0x7a, 0x04, 0x3c, 0x94, 0x80, 0xbb, 0xa4, 0xaa, 0x02, 0x0c,
	0xa4, 0x87, 0xf6, 0x1d, 0xee, 0x0c, 0x68, 0xbf, 0xe3, 0x8b, 0x1e, 0x77, 0x98, 0x3f, 0x20, 0xbf,
	0x6a, 0x50, 0xfc, 0x98, 0x7b, 0xdf, 0x32, 0xa7, 0x71, 0xd6, 0x20, 0xe5, 0xcc, 0x9c, 0x89, 0x26,
	0xc6, 0xab, 0xcc, 0x22, 0x45, 0xb2, 0x0f, 0x25, 0xd9, 0xfb, 0xe4, 0x68, 0x0a, 0x99, 0x2b, 0x5d,
	0x63, 0x68, 0xb4, 0x1f, 0x45, 0x2e, 0x86, 0xfd, 0xfc, 0x43, 0x83, 0xc5, 0xc9, 0x51, 0x4a, 0xf6,
	0x32, 0x11, 0x32, 0xa6, 0xb4, 0xbe, 0xff, 0x3f, 0x1c, 0xc8, 0x7e, 0x20, 0xd9, 0x6b, 0xa4, 0xf2,
	0xcc, 0xb6, 0xf7, 0xe4, 0x02, 0xd1, 0xee, 0xdf, 0x6a, 0x50, 0x4c, 0x66, 0xdd, 0x94, 0xa6, 0x4e,
	0x4e, 0xdc, 0x29, 0x4d, 0x4d, 0x4d, 0x5c, 0xb3, 0x26, 0xc1, 0xb6, 0xc9, 0x26, 0x55, 0x7f, 0x57,
	0xd0, 0x68, 0xb8, 0x46, 0x5b, 0x4e, 0x7e, 0xd1, 0xe0, 0xd5, 0xf1, 0xa9, 0x47, 0x6a, 0x53, 0x53,
	0x4d, 0x4c, 0x61, 0x7d, 0x77, 0x46, 0x35, 0xb2, 0xd5, 0x25, 0xdb, 0x0e, 0xd9, 0xce, 0x64, 0x8b,
	0x2d, 0x51, 0xc3, 0x7e, 0xd7, 0xe0, 0xb5, 0x89, 0x01, 0x48, 0xb2, 0xcf, 0xbf, 0x7a, 0x2e, 0xeb,
	0x7b, 0xb3, 0x1b, 0x10, 0x73, 0x5f, 0x62, 0x56, 0x49, 0x99, 0x4e, 0xf9, 0xf8, 0xa2, 0x38, 0x82,
	0x25, 0xe9, 0xc9, 0x7b, 0x77, 0x0f, 0x86, 0x76, 0xff, 0x60, 0x68, 0xff, 0x3c, 0x18, 0xda, 0xed,
	0xa3, 0x91, 0xbb, 0x7f, 0x34, 0x72, 0x7f, 0x3d, 0x1a, 0xb9, 0xaf, 0xf4, 0xd1, 0x1a, 0xdf, 0x8d,
	0x56, 0x09, 0x6f, 0x3a, 0x2c, 0xf8, 0xa6, 0x20, 0x3f, 0xe0, 0x0e, 0xff, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x4e, 0xa7, 0x16, 0xd7, 0xf8, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// DIDDocument queries a DID document by ID.
	DIDDocument(ctx context.Context, in *QueryDIDDocumentRequest, opts ...grpc.CallOption) (*QueryDIDDocumentResponse, error)
	// Credential queries a credential by ID.
	Credential(ctx context.Context, in *QueryCredentialRequest, opts ...grpc.CallOption) (*QueryCredentialResponse, error)
	// SocialIdentity queries a social identity by DID and provider.
	SocialIdentity(ctx context.Context, in *QuerySocialIdentityRequest, opts ...grpc.CallOption) (*QuerySocialIdentityResponse, error)
	// LinkedDID queries the DID linked to a social identity.
	LinkedDID(ctx context.Context, in *QueryLinkedDIDRequest, opts ...grpc.CallOption) (*QueryLinkedDIDResponse, error)
	// VerifyCredential verifies a credential.
	VerifyCredential(ctx context.Context, in *QueryVerifyCredentialRequest, opts ...grpc.CallOption) (*QueryVerifyCredentialResponse, error)
	// MFAConfig queries the MFA configuration for a DID.
	MFAConfig(ctx context.Context, in *QueryMFAConfigRequest, opts ...grpc.CallOption) (*QueryMFAConfigResponse, error)
	// MFAChallenge queries an MFA challenge by ID.
	MFAChallenge(ctx context.Context, in *QueryMFAChallengeRequest, opts ...grpc.CallOption) (*QueryMFAChallengeResponse, error)
	// RecoverySession queries a recovery session by ID.
	RecoverySession(ctx context.Context, in *QueryRecoverySessionRequest, opts ...grpc.CallOption) (*QueryRecoverySessionResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/selfchain.identity.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DIDDocument(ctx context.Context, in *QueryDIDDocumentRequest, opts ...grpc.CallOption) (*QueryDIDDocumentResponse, error) {
	out := new(QueryDIDDocumentResponse)
	err := c.cc.Invoke(ctx, "/selfchain.identity.Query/DIDDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Credential(ctx context.Context, in *QueryCredentialRequest, opts ...grpc.CallOption) (*QueryCredentialResponse, error) {
	out := new(QueryCredentialResponse)
	err := c.cc.Invoke(ctx, "/selfchain.identity.Query/Credential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SocialIdentity(ctx context.Context, in *QuerySocialIdentityRequest, opts ...grpc.CallOption) (*QuerySocialIdentityResponse, error) {
	out := new(QuerySocialIdentityResponse)
	err := c.cc.Invoke(ctx, "/selfchain.identity.Query/SocialIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LinkedDID(ctx context.Context, in *QueryLinkedDIDRequest, opts ...grpc.CallOption) (*QueryLinkedDIDResponse, error) {
	out := new(QueryLinkedDIDResponse)
	err := c.cc.Invoke(ctx, "/selfchain.identity.Query/LinkedDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifyCredential(ctx context.Context, in *QueryVerifyCredentialRequest, opts ...grpc.CallOption) (*QueryVerifyCredentialResponse, error) {
	out := new(QueryVerifyCredentialResponse)
	err := c.cc.Invoke(ctx, "/selfchain.identity.Query/VerifyCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MFAConfig(ctx context.Context, in *QueryMFAConfigRequest, opts ...grpc.CallOption) (*QueryMFAConfigResponse, error) {
	out := new(QueryMFAConfigResponse)
	err := c.cc.Invoke(ctx, "/selfchain.identity.Query/MFAConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MFAChallenge(ctx context.Context, in *QueryMFAChallengeRequest, opts ...grpc.CallOption) (*QueryMFAChallengeResponse, error) {
	out := new(QueryMFAChallengeResponse)
	err := c.cc.Invoke(ctx, "/selfchain.identity.Query/MFAChallenge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RecoverySession(ctx context.Context, in *QueryRecoverySessionRequest, opts ...grpc.CallOption) (*QueryRecoverySessionResponse, error) {
	out := new(QueryRecoverySessionResponse)
	err := c.cc.Invoke(ctx, "/selfchain.identity.Query/RecoverySession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// DIDDocument queries a DID document by ID.
	DIDDocument(context.Context, *QueryDIDDocumentRequest) (*QueryDIDDocumentResponse, error)
	// Credential queries a credential by ID.
	Credential(context.Context, *QueryCredentialRequest) (*QueryCredentialResponse, error)
	// SocialIdentity queries a social identity by DID and provider.
	SocialIdentity(context.Context, *QuerySocialIdentityRequest) (*QuerySocialIdentityResponse, error)
	// LinkedDID queries the DID linked to a social identity.
	LinkedDID(context.Context, *QueryLinkedDIDRequest) (*QueryLinkedDIDResponse, error)
	// VerifyCredential verifies a credential.
	VerifyCredential(context.Context, *QueryVerifyCredentialRequest) (*QueryVerifyCredentialResponse, error)
	// MFAConfig queries the MFA configuration for a DID.
	MFAConfig(context.Context, *QueryMFAConfigRequest) (*QueryMFAConfigResponse, error)
	// MFAChallenge queries an MFA challenge by ID.
	MFAChallenge(context.Context, *QueryMFAChallengeRequest) (*QueryMFAChallengeResponse, error)
	// RecoverySession queries a recovery session by ID.
	RecoverySession(context.Context, *QueryRecoverySessionRequest) (*QueryRecoverySessionResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) DIDDocument(ctx context.Context, req *QueryDIDDocumentRequest) (*QueryDIDDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DIDDocument not implemented")
}
func (*UnimplementedQueryServer) Credential(ctx context.Context, req *QueryCredentialRequest) (*QueryCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Credential not implemented")
}
func (*UnimplementedQueryServer) SocialIdentity(ctx context.Context, req *QuerySocialIdentityRequest) (*QuerySocialIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SocialIdentity not implemented")
}
func (*UnimplementedQueryServer) LinkedDID(ctx context.Context, req *QueryLinkedDIDRequest) (*QueryLinkedDIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkedDID not implemented")
}
func (*UnimplementedQueryServer) VerifyCredential(ctx context.Context, req *QueryVerifyCredentialRequest) (*QueryVerifyCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyCredential not implemented")
}
func (*UnimplementedQueryServer) MFAConfig(ctx context.Context, req *QueryMFAConfigRequest) (*QueryMFAConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MFAConfig not implemented")
}
func (*UnimplementedQueryServer) MFAChallenge(ctx context.Context, req *QueryMFAChallengeRequest) (*QueryMFAChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MFAChallenge not implemented")
}
func (*UnimplementedQueryServer) RecoverySession(ctx context.Context, req *QueryRecoverySessionRequest) (*QueryRecoverySessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverySession not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfchain.identity.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DIDDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDIDDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DIDDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfchain.identity.Query/DIDDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DIDDocument(ctx, req.(*QueryDIDDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Credential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Credential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfchain.identity.Query/Credential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Credential(ctx, req.(*QueryCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SocialIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySocialIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SocialIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfchain.identity.Query/SocialIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SocialIdentity(ctx, req.(*QuerySocialIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LinkedDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLinkedDIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LinkedDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfchain.identity.Query/LinkedDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LinkedDID(ctx, req.(*QueryLinkedDIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifyCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifyCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifyCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfchain.identity.Query/VerifyCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifyCredential(ctx, req.(*QueryVerifyCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MFAConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMFAConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MFAConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfchain.identity.Query/MFAConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MFAConfig(ctx, req.(*QueryMFAConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MFAChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMFAChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MFAChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfchain.identity.Query/MFAChallenge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MFAChallenge(ctx, req.(*QueryMFAChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RecoverySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRecoverySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RecoverySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/selfchain.identity.Query/RecoverySession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RecoverySession(ctx, req.(*QueryRecoverySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "selfchain.identity.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "DIDDocument",
			Handler:    _Query_DIDDocument_Handler,
		},
		{
			MethodName: "Credential",
			Handler:    _Query_Credential_Handler,
		},
		{
			MethodName: "SocialIdentity",
			Handler:    _Query_SocialIdentity_Handler,
		},
		{
			MethodName: "LinkedDID",
			Handler:    _Query_LinkedDID_Handler,
		},
		{
			MethodName: "VerifyCredential",
			Handler:    _Query_VerifyCredential_Handler,
		},
		{
			MethodName: "MFAConfig",
			Handler:    _Query_MFAConfig_Handler,
		},
		{
			MethodName: "MFAChallenge",
			Handler:    _Query_MFAChallenge_Handler,
		},
		{
			MethodName: "RecoverySession",
			Handler:    _Query_RecoverySession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "selfchain/identity/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDIDDocumentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDIDDocumentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDIDDocumentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDIDDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDIDDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDIDDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Document.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryCredentialRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCredentialRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCredentialRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryCredentialResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCredentialResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCredentialResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Credential.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryVerifyCredentialRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifyCredentialRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifyCredentialRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVerifyCredentialResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVerifyCredentialResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVerifyCredentialResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *VerificationStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerificationStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerificationStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x12
	}
	if m.Valid {
		i--
		if m.Valid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryMFAConfigRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMFAConfigRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMFAConfigRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMFAConfigResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMFAConfigResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMFAConfigResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMFAChallengeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMFAChallengeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMFAChallengeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMFAChallengeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMFAChallengeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMFAChallengeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Challenge.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRecoverySessionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoverySessionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoverySessionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRecoverySessionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRecoverySessionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRecoverySessionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Session.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDIDDocumentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDIDDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Document.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryCredentialRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCredentialResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Credential.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryVerifyCredentialRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVerifyCredentialResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Status.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *VerificationStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Valid {
		n += 2
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMFAConfigRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMFAConfigResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Config.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMFAChallengeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMFAChallengeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Challenge.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRecoverySessionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRecoverySessionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Session.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDIDDocumentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDIDDocumentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDIDDocumentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDIDDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDIDDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDIDDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Document", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Document.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCredentialRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCredentialRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCredentialRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCredentialResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCredentialResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCredentialResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credential", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Credential.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifyCredentialRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifyCredentialRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifyCredentialRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVerifyCredentialResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVerifyCredentialResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVerifyCredentialResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerificationStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerificationStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerificationStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Valid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Valid = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMFAConfigRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMFAConfigRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMFAConfigRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMFAConfigResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMFAConfigResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMFAConfigResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMFAChallengeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMFAChallengeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMFAChallengeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMFAChallengeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMFAChallengeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMFAChallengeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challenge", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Challenge.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecoverySessionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoverySessionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoverySessionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRecoverySessionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRecoverySessionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRecoverySessionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Session.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
